import { useEffect, useRef, useState } from 'react';
import { VoiceController } from './VoiceController';
export function useVoice(onTranscript) {
  const controller = useRef(new VoiceController()).current; const recognition = useRef(null); const keepListening = useRef(false); const speaking = useRef(false); const callback = useRef(onTranscript); callback.current = onTranscript;
  const [listening, setListening] = useState(false); const [isSpeaking, setSpeaking] = useState(false); const [enabled, setEnabled] = useState(false); const [error, setError] = useState('');
  function startRecognition() { if (!keepListening.current || speaking.current) return; const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!Recognition) return; const instance = new Recognition(); recognition.current = instance; instance.lang = navigator.language || 'en-US'; instance.continuous = true; instance.interimResults = false; instance.maxAlternatives = 1;
    instance.onstart = () => setListening(true);
    instance.onresult = async event => { const result = event.results[event.results.length - 1]; if (!result?.isFinal) return; const text = result[0].transcript.trim(); if (!text) return; speaking.current = true; instance.stop(); setListening(false); callback.current(text); setSpeaking(true); await controller.speak(text); setSpeaking(false); speaking.current = false; if (keepListening.current) startRecognition(); };
    instance.onerror = event => { if (event.error === 'not-allowed' || event.error === 'service-not-allowed') { keepListening.current = false; setEnabled(false); setError('Microphone permission was blocked. Enable it for this site in your browser settings, then try again.'); } else if (event.error === 'network') { keepListening.current = false; setEnabled(false); setError('Your browser speech service is unavailable. Check your connection and try again.'); } else if (event.error !== 'aborted' && event.error !== 'no-speech') setError('Voice recognition paused. Tap the voice indicator to resume.'); };
    instance.onend = () => { setListening(false); if (keepListening.current && !speaking.current) window.setTimeout(startRecognition, 180); };
    try { instance.start(); } catch { keepListening.current = false; setEnabled(false); setError('Voice recognition could not start. Reload the page and try again.'); }
  }
  async function enableHandsFree() { setError(''); if (!controller.secureContext) { setError('Mobile browsers block microphone access on HTTP. Open this game through HTTPS (or use localhost directly on the same device), then try again.'); return; } if (!controller.recognitionSupported) { setError('This browser can use the microphone but does not provide speech recognition. Chrome on Android supports this flow; iPhone browsers need a server speech-to-text provider.'); return; } try { await controller.requestMicrophone(); keepListening.current = true; setEnabled(true); startRecognition(); } catch (error) { if (error.message === 'MICROPHONE_UNSUPPORTED') setError('Microphone access is unavailable in this browser.'); else if (error.message === 'SECURE_CONTEXT_REQUIRED') setError('Mobile browsers block microphone access on HTTP. Open this game through HTTPS.'); else setError('Microphone permission is needed for hands-free chat. Nothing is recorded or saved.'); } }
  function stopHandsFree() { keepListening.current = false; recognition.current?.abort(); controller.stopSpeaking(); setListening(false); setSpeaking(false); setEnabled(false); }
  useEffect(() => () => stopHandsFree(), []);
  return { listening, speaking: isSpeaking, enabled, error, enableHandsFree, stopHandsFree, supported: controller.recognitionSupported };
}
