from abc import ABC, abstractmethod
class CartoonProvider(ABC):
    @abstractmethod
    async def generate_avatar(self, image_bytes: bytes): ...
    @abstractmethod
    async def get_status(self): ...
    @abstractmethod
    async def cancel_job(self, job_id: str): ...
